services:
  redis:
    image: redis:7.4.0-alpine
    container_name: pybase_redis_local
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
      - pybase_redis_local:/data
    networks:
      - pybase
  postgres:
    container_name: pybase_postgres_local
    image: postgres:16.4-bullseye
    shm_size: 1g
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pybase
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./.docker/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - pybase_postgres_local:/var/lib/postgresql/data
    networks:
      - pybase
  pgadmin:
    container_name: pybase_pgadmin_local
    image: dpage/pgadmin4:8.10
    shm_size: 1g
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pybase_pgadmin_local:/var/lib/pgadmin
    networks:
      - pybase
networks:
  pybase:
volumes:
  pybase_postgres_local:
  pybase_redis_local:
  pybase_pgadmin_local:
