# Generated by Django 5.0.7 on 2024-07-15 09:02
from asgiref.sync import async_to_sync
from django.db import migrations
from projectmanagement.data.import_data import ImportData


def create_questions(apps, schema_editor):
    # create questions
    i = ImportData()
    async_to_sync(i.import_questions_async)()


class Migration(migrations.Migration):
    dependencies = [
        ('projectmanagement', '0002_taggeditem'),
    ]

    operations = [
        migrations.RunPython(create_questions)
    ]
