# Generated by Django 5.0.7 on 2024-07-15 09:02

from django.db import migrations
from typing import Type, cast
from ..models import Question


def create_questions(apps, schema_editor):
    # create questions
    QuestionModel = apps.get_model('projectmanagement', 'Question')
    QuestionModel = cast(Type[Question], QuestionModel)
    # Now use QuestionModel with type hints
    new_question = QuestionModel.objects.create(
    )
    Question.objects.create(
        title='',
        multiple_choices=True
    )
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('projectmanagement', '0002_taggeditem'),
    ]

    operations = [
        migrations.RunPython(create_questions)
    ]
